### PR TITLE
Stay

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
good

**Review by ghost — COMMENTED** [review]
https://github.com/shenruisi/Stay-Offical-Userscript/pull/6/files?short_path=1488707#diff-148870715557a13127284f8aeaa28002ed6b034268af13c5d030ab59fd078220

**Review by ghost — COMMENTED** [review]
g

**Comment by jzxo** [comment]
is very good

**Pull request closed without merging**
